find_path(CLOG_INCLUDE_DIR clog.h /usr/local/include/clog /usr/include/clog)
find_library(CLOG_LIBS clog /usr/local/lib /usr/lib)
get_filename_component(CLOG_LIBRARY_DIR ${CLOG_LIBS} PATH)
if(CLOG_INCLUDE_DIR)
	if(CLOG_LIBS)
		set(CLOG_FOUND "YES")
	endif()
endif()
